package com.example.demo;
// Generated 03/06/2019 20:08:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="spring"
)
public class Produto  implements java.io.Serializable {


     private Long idProduto;
     private String nome;
     private String fabricante;
     private Double valorUnitario;
     private Integer qtdEstoque;

    public Produto() {
    }

    public Produto(String nome, String fabricante, Double valorUnitario, Integer qtdEstoque) {
       this.nome = nome;
       this.fabricante = fabricante;
       this.valorUnitario = valorUnitario;
       this.qtdEstoque = qtdEstoque;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produto", unique=true, nullable=false)
    public Long getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Long idProduto) {
        this.idProduto = idProduto;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="fabricante", length=45)
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }

    
    @Column(name="valor_unitario", precision=22, scale=0)
    public Double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(Double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    
    @Column(name="qtd_estoque")
    public Integer getQtdEstoque() {
        return this.qtdEstoque;
    }
    
    public void setQtdEstoque(Integer qtdEstoque) {
        this.qtdEstoque = qtdEstoque;
    }




}


